logging:
  file: logs/zuul/zuul.log
  level:
    com.importexpress: info

server:
  port: 18005
spring:
  application:
    name: gateway-zuul
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone:   http://127.0.0.1:18000/eureka
    registry-fetch-interval-seconds: 5
zuul:
  debug:
    request: true  #如果设置了这个，默认所有的请求都会debug
  include-debug-header: true

  prefix: /api
  retryable: true
  routes:
    ali1688-service: /ali-service/**
    cart-service: /cart-service/**
    utils-service: /utils-service/**
    search-service: /search-service/**
    email-service: /email-service/**
    pay-service: /pay-service/**
    product-service: /product-service/**
    shopify-service: /shopify-service/**

  ribbon:
    eager-load:
      enabled: true
  ignored-services: /**

ribbon:
  ConnectTimeout: 250
  ReadTimeout: 600000 #10 mins
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 10000
